# Generated by Django 5.1.1 on 2025-09-12 07:53

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_app", "0002_add_frozenState"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="refund_balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_pic",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="profile_pic"
            ),
        ),
    ]
